package com.auction.entities.msg;

public enum EventType {
    TASK_SEND_MAIL_OTP,
    TASK_SEND_MAIL_SUCCESS_BID,
    TASK_SEND_MAIL_OUTBID,
    TASK_SEND_MAIL_ACCOUNT_VIOLATION,
    TASK_SEND_NOTIFICATION,
    TASK_DELETE_NOTIFICATION,
    TASK_READ_NOTIFICATION,
}
