syntax = "proto3";

// Tên package logical của file proto
package auth;

option java_multiple_files = true;
option java_package = "com.auction.proto.auth";
option java_outer_classname = "AuthProto";

// --- Service Definition ---
service AuthService {
  // 1. Đăng ký tài khoản mới
  rpc Register (RegisterRequest) returns (RegisterResponse);

  // 2. Đăng nhập (trả về Access + Refresh Token)
  rpc Login (LoginRequest) returns (LoginResponse);

  // 3. Cấp lại Access Token mới bằng Refresh Token
  rpc RefreshToken (RefreshTokenRequest) returns (RefreshTokenResponse);

  // 4. Đăng xuất (Thu hồi Refresh Token)
  rpc Logout (LogoutRequest) returns (LogoutResponse);

  // 5. Kiểm tra Token hợp lệ (Dùng cho Gateway hoặc Service khác gọi internal)
  rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenResponse);

  // 6. Đổi mật khẩu
  rpc ChangePassword (ChangePasswordRequest) returns (ChangePasswordResponse);

  // 7. Xác minh OTP
  rpc VerifyOTP (VerifyOTPRequest) returns (VerifyOTPResponse);

  // 8. Cấp lại OTP
  rpc reproduceOTP (ReproduceOTPRequest) returns (ReproduceOTPResponse);
}

// --- Message Definitions ---

// 1. REGISTER
message RegisterRequest {
  string email = 1;
  string password = 2;
  string full_name = 3;
  string phone_number = 4;
  string address = 5;
}

message RegisterResponse {
  string user_id = 1;
  string email = 2;
  bool success = 3;
  string message = 4;
  string otp = 5; // OTP 6 chữ số được gửi qua email, hết hạn sau 10 phút
}

// 2. LOGIN
message LoginRequest {
  string email = 1;
  string password = 2;
}

message LoginResponse {
  string access_token = 1;
  string refresh_token = 2;
  string message = 3;
  UserInfo user_info = 5;
}

message UserInfo {
  string id = 1;
  string email = 2;
  string full_name = 3;
  repeated string roles = 4;
}

// 3. REFRESH TOKEN
message RefreshTokenRequest {
  string refresh_token = 1;
}

message RefreshTokenResponse {
  string access_token = 1;
  string refresh_token = 2;
  string message = 3;
  int64 access_token_expires_in = 4;
}

// 4. LOGOUT
message LogoutRequest {
  string refresh_token = 1; // Logout cần revoke refresh token trong DB/Redis
  string user_id = 2;
}

message LogoutResponse {
  bool success = 1;
  string message = 2;
}

message ValidateTokenRequest {
  string access_token = 1;
}

message ValidateTokenResponse {
  bool is_valid = 1;
  string user_id = 2;
  repeated string roles = 3;
  string error_message = 4;
}

// 6. CHANGE PASSWORD
message ChangePasswordRequest {
  string user_id = 1;
  string old_password = 2;
  string new_password = 3;
}

message ChangePasswordResponse {
  bool success = 1;
  string message = 2;
}

// 7. VERIFY OTP
message VerifyOTPRequest {
  string email = 1;
  string otp = 2; // OTP 6 chữ số
}

message VerifyOTPResponse {
  bool success = 1;
  string message = 2;
}

// 8. Reproduce OTP
message ReproduceOTPRequest {
  string email = 1;
}

message ReproduceOTPResponse {
  bool success = 1;
  string message = 2;
}