syntax = "proto3";

package com.auctionplatform.payment.grpc;

option java_multiple_files = true;
option java_package = "com.auctionplatform.payment.grpc";
option java_outer_classname = "PaymentServiceProto";

service PaymentService {
    // update payment order status
  rpc UpdateOrderStatus(UpdateOrderStatusRequest) returns (UpdateOrderStatusResponse);
}

message UpdateOrderStatusRequest {
  int32 order_id = 1;
  string status = 2;
}

message UpdateOrderStatusResponse {
  bool success = 1;
  string message = 2;
  int32 order_id = 3;
  string status = 4;
}
