spring.application.name=products

# R2DBC MySQL Configuration
spring.r2dbc.url=r2dbc:mysql://localhost:3306/mydb
spring.r2dbc.username=root
spring.r2dbc.password=root123
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m


