spring:
  application:
    name: chat
  
  datasource:
    url: jdbc:postgresql://${CHAT_DB_HOST:localhost}:${CHAT_DB_PORT:5434}/chatdb
    username: ${CHAT_DB_USER:chat_user}
    password: ${CHAT_DB_PASSWORD:chat_pass}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${CHAT_SERVICE_PORT:8085}

logging:
  level:
    chat: INFO
    org.springframework.web.socket: DEBUG


